image: gitpod/workspace-dotnet:latest
vscode:
  extensions:
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
    - syler.sass-indented
tasks:
  - name: Download .NET SDKS
    # init: |
    #   curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 3.1.402 --install-dir /home/gitpod/dotnet/
    #   curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 5.0.401 --install-dir /home/gitpod/dotnet/
  - command: rm paket-files/ -rf && dotnet tool restore && dotnet fake run build.fsx -t Install -p 2
ports:
  - port: 9060
    onOpen: open-browser
    visibility: public
  - port: 7899
    onOpen: ignore
    visibility: public
  - port: 7412
    onOpen: ignore
    visibility: public
  - port: 9856
    onOpen: ignore
    visibility: public
  - port: 11084
    onOpen: ignore
    visibility: public
  - port: 2568
    onOpen: ignore
    visibility: public
  - port: 9007
    onOpen: ignore
    visibility: public
  - port: 10707
    onOpen: ignore
    visibility: public
