image: nojaf/fable-azure-functions:1.1
vscode:
  extensions:
    - muhammad-sammy.csharp
    - ionide.ionide-fsharp
    - syler.sass-indented
tasks:
  - command: rm paket-files/ -rf && dotnet tool restore && dotnet fake run build.fsx -t Install -p 2
ports:
  - port: 9060
    onOpen: open-browser 
  - port: 7899
    onOpen: ignore
  - port: 7412
    onOpen: ignore
  - port: 9856
    onOpen: ignore
  - port: 11084
    onOpen: ignore
  - port: 2568
    onOpen: ignore
  - port: 9007
    onOpen: ignore
  - port: 10707
    onOpen: ignore
